added role based access, User entity, JWT-based authentication,  fixe…
DmytroFedoryshyn/bookstore pull request #10
Opened 2023-08-23 15:34 UTC by DmytroFedoryshyn

…d book sorting

2023-08-23 15:38 UTC, DmytroFedoryshyn commented
For some reason, CI checks fail. When I run mvn clean package on my machine, it works perfectly

2023-08-23 17:58 UTC, aaananas commented
Did you push all the changes? pom.xml etc

2023-08-24 11:09 UTC, Rommelua requested changes

2023-08-24 11:09 UTC, Rommelua commented on src/main/java/bookstore/dto/UserLoginRequestDto.java
> +    @Size(min = 8, max = 50)
there are all checks inside @Email
```suggestion
```

2023-08-24 11:09 UTC, Rommelua commented on src/main/java/bookstore/dto/UserRegistrationRequest.java
> +    @Size(min = 4, max = 50)
```suggestion
```

2023-08-24 11:09 UTC, Rommelua commented on src/main/java/bookstore/dto/UserRegistrationRequest.java
> +    @Size(min = 6, max = 100)
```suggestion
```

2023-08-24 11:09 UTC, Rommelua commented on src/main/java/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-08-24 11:09 UTC, Rommelua commented on src/main/java/bookstore/repository/user/UserRepository.java
> +    @Query("FROM User u LEFT JOIN FETCH u.roles WHERE u.email = :email AND u.isDeleted = false")
```suggestion
    @EntityGraph(attributePaths = "roles")
```

2023-08-28 13:56 UTC, merged