added categories
DmytroFedoryshyn/bookstore pull request #13
Opened 2023-08-28 15:38 UTC by DmytroFedoryshyn

2023-08-29 11:06 UTC, Rommelua requested changes

2023-08-29 11:06 UTC, Rommelua commented on src/main/java/bookstore/controller/CategoryController.java
> +    public CategoryResponseDto createCategory(@Valid @RequestBody
PreAuthorize?

2023-08-29 11:06 UTC, Rommelua commented on src/main/java/bookstore/controller/CategoryController.java
> +    public CategoryResponseDto updateCategory(@PathVariable Long id,
PreAuthorize?

2023-08-29 11:06 UTC, Rommelua commented on src/main/java/bookstore/mapper/BookMapper.java
> +                })
```suggestion
                .map(Category ::new)
```

2023-08-29 11:06 UTC, Rommelua commented on src/main/java/bookstore/service/CategoryServiceImpl.java
> +        Category category = mapper.toEntity(categoryDto);
```suggestion
    public CategoryResponseDto update(Long id, CreateCategoryRequestDto categoryDto) {
            Category dbCategory = categoryRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Category not found with ID: " + id));
        Category category = mapper.toEntity(categoryDto);
```

2023-08-29 17:09 UTC, aaananas requested changes

2023-08-29 17:09 UTC, aaananas commented on src/main/java/bookstore/model/Category.java
> +@RequiredArgsConstructor
```suggestion
@NoArgsConstructor
```
RequiredArgsConstructor creates a constructor with final fields. In your case you should use NoArgsConstructor

2023-08-29 17:09 UTC, aaananas commented on src/main/java/bookstore/repository/book/BookRepository.java
> +    List<Book> findAllByCategories_Id(Long id, Pageable pageable);
```suggestion
    List<Book> findAllByCategoryId(Long id, Pageable pageable);
```

2023-08-29 17:09 UTC, aaananas commented on src/main/java/bookstore/service/BookServiceImpl.java
> +    public List<BookResponseDtoWithoutCategoryIds> findAllByCategories_Id(
```suggestion
    public List<BookResponseDtoWithoutCategoryIds> findAllByCategoryId(
```

2023-08-29 17:09 UTC, aaananas commented on src/main/java/bookstore/dto/book/BookResponseDtoWithoutCategoryIds.java
> +public class BookResponseDtoWithoutCategoryIds {
```suggestion
public class BaseBookResponseDto {
```

2023-08-30 09:59 UTC, Rommelua approved these changes

2023-08-30 15:52 UTC, merged